default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# Development uses MySQL
development:
  <<: *default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  database: <%= ENV['MYSQL_DATABASE'] %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: mysql_db

# Test and Production use Postgres
test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: todo_list_text_production
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
